AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation template to create an S3 bucket


Resources:
  SimpleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
Parameters:
  BucketName:
    Type: String
